import {serializeState,normalizeRestaurant,validateFieldSettings,restaurantValue} from '../model.js';
import {clone,fail,hashValue,canonicalJson,parseStrictJson,assertExactKeys,decodeUtf8,decodeBase64,byteLength,VALUE_KEYS,ELIGIBLE_FIELDS,MAX_SESSION_BYTES,uniqueIds,textLimit,stringList} from './common.js';
import {readResearchCsv,projectPublicRow} from './source.js';
import {validateExchange,dateValid} from './exchange.js';
import {PUBLIC_RESEARCH_PROMPT,PUBLIC_RESEARCH_PROMPT_VERSION} from './prompt.js';
const ROOT=['format','schemaVersion','notebook','recordBindings','source','workspaceId','runManifest','candidates','applicationReceipts'];
const CANDIDATE=['sourceRow','baseRestaurant','status','validationErrors','id','revision','activeRequest','result','review','urlJobs','targetRecordId','history','rawReceipt'];
const RECEIPT=['workspaceId','candidateId','acceptedRequestId','targetRecordId','policyRevision','patchHash','beforeFieldVersions','afterFieldVersions','beforeFieldHashes','afterFieldHashes'];
const STATES=['waiting','running','confirmed','needs_review','failed','cancelled','invalid'];
const empty=v=>canonicalJson(v)==='{}';
const equal=(a,b)=>canonicalJson(a)===canonicalJson(b);
const checkedId=id=>{textLimit(id,200);if(!id)fail('ID','空の識別子です。');};
function maps(versions,hashes){assertExactKeys(versions,VALUE_KEYS);assertExactKeys(hashes,VALUE_KEYS);for(const k of VALUE_KEYS)if(!Number.isSafeInteger(versions[k])||versions[k]<0||! /^[a-f0-9]{64}$/.test(hashes[k]))fail('BINDING','項目revision・hashが不正です。');}
export async function serializeResearchSession(notebook,session){
 const book=JSON.parse(serializeState(notebook).json),root={format:'gourmet-notebook-research-session',schemaVersion:1,notebook:book,recordBindings:clone(session.recordBindings),source:clone(session.source),workspaceId:session.workspaceId,runManifest:clone(session.runManifest),candidates:clone(session.candidates),applicationReceipts:clone(session.applicationReceipts)};
 const json=JSON.stringify(root),bytes=byteLength(json);if(bytes>MAX_SESSION_BYTES)fail('SESSION_CAPACITY','研究作業全体が16 MiBを超えます。');await restoreResearchSession(new TextEncoder().encode(json),'session.json');return {json,bytes};
}
export async function restoreResearchSession(bytes,filename){
 if(typeof filename!=='string'||!filename.toLowerCase().endsWith('.json'))fail('BACKUP_FILE','研究作業JSONを選択してください。');const root=parseStrictJson(decodeUtf8(bytes,MAX_SESSION_BYTES),{maxBytes:MAX_SESSION_BYTES});assertExactKeys(root,ROOT);if(root.format!=='gourmet-notebook-research-session'||root.schemaVersion!==1)fail('BACKUP_SCHEMA','研究作業backupの形式が必要です。');checkedId(root.workspaceId);
 const book=assertExactKeys(root.notebook,['schemaVersion','format','fieldSettings','restaurants']);if(book.schemaVersion!==2||book.format!=='gourmet-notebook-prototype'||!Array.isArray(book.restaurants)||!Array.isArray(root.recordBindings)||book.restaurants.length!==root.recordBindings.length)fail('BOOK','手帳とID台帳の対応が不正です。');
 const settings=validateFieldSettings(book.fieldSettings);if(!equal(settings,book.fieldSettings))fail('SETTINGS','項目設定が正規化済みではありません。');uniqueIds(root.recordBindings,'recordId');const stores=[];
 for(let i=0;i<book.restaurants.length;i++){const r=book.restaurants[i];assertExactKeys(r,VALUE_KEYS);const normalized=normalizeRestaurant(r,settings);if(!equal(normalized,r))fail('BOOK_VALUE','正規化済みの店舗値が必要です。');const b=assertExactKeys(root.recordBindings[i],['recordId','fieldVersions','fieldValueHashes','protectedFields']);checkedId(b.recordId);maps(b.fieldVersions,b.fieldValueHashes);stringList(b.protectedFields,8,20);if(new Set(b.protectedFields).size!==b.protectedFields.length||b.protectedFields.some(k=>!VALUE_KEYS.includes(k)))fail('PROTECTION','保護項目が不正です。');for(const k of VALUE_KEYS)if(await hashValue(r[k])!==b.fieldValueHashes[k])fail('BOOK_HASH','台帳と現在値のhashが一致しません。');stores.push({...normalized,id:b.recordId,source:'研究作業復元',icon:'◌',tone:'green'});}
 const notebook={fieldSettings:settings,stores};serializeState(notebook);
 const source=assertExactKeys(root.source,['filename','mediaType','byteLength','sha256','columns','emptyRecords','bytesBase64']);textLimit(source.filename,1000);const original=decodeBase64(source.bytesBase64),extracted=await readResearchCsv(original,source.filename,settings);if(!equal(source,extracted.source))fail('SOURCE_HASH','原本バイト・hash・行位置が一致しません。');
 const manifest=assertExactKeys(root.runManifest,['kind','createdAt','promptVersion','promptHash','applyPolicy']);if(!['local-json-exchange','saved-observation-conversion'].includes(manifest.kind)||!dateValid(manifest.createdAt)||manifest.promptVersion!==PUBLIC_RESEARCH_PROMPT_VERSION||manifest.promptHash!==await hashValue(PUBLIC_RESEARCH_PROMPT))fail('MANIFEST','実行manifestが不正です。');
 const policy=assertExactKeys(manifest.applyPolicy,['revision','allowSequential','allowedFields','confirmedAt']);if(!Number.isSafeInteger(policy.revision)||policy.revision<0||typeof policy.allowSequential!=='boolean'||!Array.isArray(policy.allowedFields)||new Set(policy.allowedFields).size!==policy.allowedFields.length||policy.allowedFields.some(k=>!ELIGIBLE_FIELDS.includes(k))||policy.confirmedAt!==''&&!dateValid(policy.confirmedAt)||policy.allowSequential&&(!policy.confirmedAt||!policy.revision))fail('POLICY','補完方針が不正です。');
 if(!Array.isArray(root.candidates)||root.candidates.length!==extracted.candidates.length)fail('CANDIDATES','原本と候補行の数が違います。');uniqueIds(root.candidates);const recordIds=new Set(root.recordBindings.map(b=>b.recordId)),requestIds=new Set(),jobIds=new Set(),validatedResults=new Map();
 for(let i=0;i<root.candidates.length;i++){
  const c=assertExactKeys(root.candidates[i],CANDIDATE),e=extracted.candidates[i];checkedId(c.id);if(!Number.isSafeInteger(c.revision)||c.revision<0||!STATES.includes(c.status)||!equal(c.sourceRow,e.sourceRow)||!equal(c.baseRestaurant,e.baseRestaurant)||!equal(c.validationErrors,e.validationErrors)||c.targetRecordId&&!recordIds.has(c.targetRecordId))fail('CANDIDATE','候補行の原値・状態・対象が不正です。');
  if(!Array.isArray(c.history)||!Array.isArray(c.urlJobs)||c.urlJobs.length!==e.baseRestaurant.urls.length)fail('HISTORY','URLjob・履歴が不正です。');const attempts=new Map();
  for(const a of c.history){assertExactKeys(a,['transport','settingsSnapshot','createdAt','startedAt','status','resultHash']);assertExactKeys(a.transport,['inputHash','request']);const r=assertExactKeys(a.transport.request,['researchMode','promptVersion','requestId','workspaceId','candidateId','candidateRevision','urlJobId','settingsHash','inputProfile','sourceRedacted','sharedColumns','sourceRow','fieldDefinitions']);checkedId(r.requestId);if(requestIds.has(r.requestId))fail('REQUEST_DUPLICATE','要求IDが重複しています。');requestIds.add(r.requestId);attempts.set(r.requestId,a);
   if(r.workspaceId!==root.workspaceId||r.candidateId!==c.id||!Number.isSafeInteger(r.candidateRevision)||r.candidateRevision<1||r.candidateRevision>c.revision||r.researchMode!=='public_research'||r.promptVersion!==PUBLIC_RESEARCH_PROMPT_VERSION||r.inputProfile!=='source-projected'||r.sourceRedacted!==true||!equal(r.sharedColumns,['タイトル','URL'])||!equal(r.fieldDefinitions,[])||!dateValid(a.createdAt)||a.startedAt!==''&&!dateValid(a.startedAt)||!STATES.includes(a.status)||a.resultHash!==''&&! /^[a-f0-9]{64}$/.test(a.resultHash)||!equal(validateFieldSettings(a.settingsSnapshot),a.settingsSnapshot)||await hashValue(a.settingsSnapshot)!==r.settingsHash||await hashValue(r)!==a.transport.inputHash||byteLength(canonicalJson(r))+byteLength(PUBLIC_RESEARCH_PROMPT)>32768)fail('REQUEST','保存要求の識別値・hashが不正です。');
  }
  for(let j=0;j<c.urlJobs.length;j++){const job=assertExactKeys(c.urlJobs[j],['id','url','urlHash','status','activeRequestId','attempts']);checkedId(job.id);if(jobIds.has(job.id))fail('JOB','URLjob IDが重複しています。');jobIds.add(job.id);if(job.url!==e.baseRestaurant.urls[j]||job.urlHash!==await hashValue(job.url)||!STATES.includes(job.status)||!Array.isArray(job.attempts))fail('JOB','URLjobが原URLに対応しません。');uniqueIds(job.attempts.map(a=>({id:a.transport?.request.requestId})));for(const a of job.attempts){const r=a.transport?.request;if(!r||r.urlJobId!==job.id||!equal(a,attempts.get(r.requestId))||!equal(r.sourceRow,projectPublicRow(c.sourceRow,job.url)))fail('JOB_REQUEST','要求とURLjobの対応が違います。');}if(job.activeRequestId&&!job.attempts.some(a=>a.transport.request.requestId===job.activeRequestId))fail('JOB_ACTIVE','有効URL要求がありません。');}
  if(c.history.some(a=>!c.urlJobs.some(j=>j.attempts.some(b=>equal(a,b)))))fail('ORPHAN_REQUEST','URLjobにない要求です。');
  if(!empty(c.activeRequest)){const id=c.activeRequest.transport?.request.requestId;if(!equal(c.activeRequest,attempts.get(id))||!c.urlJobs.some(j=>j.activeRequestId===id)||c.activeRequest.transport.request.candidateRevision!==c.revision||c.status==='cancelled')fail('ACTIVE_REQUEST','有効要求の対応が不正です。');}
  const review=c.review;if(!review||Object.keys(review).some(k=>!['applyStatus','identityChecks','requestBindings','results','rawMode','receivedAt','cancelledAt','targetNeedsConfirmation','manualEdits'].includes(k))||!['unapplied','raw_registered','applied','held','failed'].includes(review.applyStatus)||!Array.isArray(review.identityChecks)||typeof review.targetNeedsConfirmation!=='boolean'||!Array.isArray(review.manualEdits)||!review.requestBindings||!review.results)fail('REVIEW','確認記録が不正です。');
  for(const [id,b]of Object.entries(review.requestBindings)){assertExactKeys(b,['recordId','fieldVersions','fieldValueHashes','protectedFields']);if(!attempts.has(id)||b.recordId!==c.targetRecordId)fail('CAPTURE','要求時の対象が違います。');maps(b.fieldVersions,b.fieldValueHashes);stringList(b.protectedFields,8,20);}
  for(const [id,v]of Object.entries(review.results)){const a=attempts.get(id);if(!a)fail('RESULT_HISTORY','対応要求のない結果です。');const checked=await validateExchange(v.exchange,a.transport,a.settingsSnapshot);if(!equal(checked,v)||v.resultHash!==a.resultHash)fail('RESULT_HISTORY','結果履歴の検証値が違います。');validatedResults.set(id,checked);}
  if(!empty(c.result)){const id=c.result.exchange?.requestId;if(!equal(c.result,review.results[id]))fail('RESULT','現在結果が履歴と違います。');}
 }
 if(!Array.isArray(root.applicationReceipts))fail('RECEIPTS','適用台帳がありません。');const receiptIds=new Set();
 for(const r of root.applicationReceipts){assertExactKeys(r,RECEIPT);const c=root.candidates.find(c=>c.id===r.candidateId),b=root.recordBindings.find(b=>b.recordId===r.targetRecordId),key=r.candidateId+':'+r.acceptedRequestId;if(!c||!b||r.workspaceId!==root.workspaceId||c.targetRecordId!==r.targetRecordId||receiptIds.has(key)||!Number.isSafeInteger(r.policyRevision)||r.policyRevision<0||r.policyRevision>policy.revision)fail('RECEIPT_REF','適用台帳の対応が不正です。');receiptIds.add(key);maps(r.beforeFieldVersions,r.beforeFieldHashes);maps(r.afterFieldVersions,r.afterFieldHashes);
  let patch={};if(r.acceptedRequestId==='raw-only'){if(!equal(c.rawReceipt,r)||!['new','existing'].includes(c.review.rawMode))fail('RAW_RECEIPT','原値登録台帳が違います。');if(c.review.rawMode==='new')patch=c.baseRestaurant;}else{const v=validatedResults.get(r.acceptedRequestId);if(!v||v.exchange.candidateId!==c.id||!v.identityVerified)fail('APPLY_RECEIPT','対応する検証済み結果がありません。');for(const k of VALUE_KEYS)if(r.afterFieldVersions[k]!==r.beforeFieldVersions[k]){if(!ELIGIBLE_FIELDS.includes(k)||r.afterFieldVersions[k]!==r.beforeFieldVersions[k]+1||!v.eligibleFields.includes(k))fail('RECEIPT_FIELDS','補完項目のrevisionが不正です。');patch[k]=v.exchange.result.restaurant[k];if(await hashValue(patch[k])!==r.afterFieldHashes[k])fail('RECEIPT_HASH','補完値hashが違います。');}}
  if(await hashValue(patch)!==r.patchHash)fail('PATCH_HASH','反映patchのhashが違います。');for(const k of VALUE_KEYS){if(!Object.hasOwn(patch,k)&&r.beforeFieldHashes[k]!==r.afterFieldHashes[k]||r.afterFieldVersions[k]<r.beforeFieldVersions[k]||b.fieldVersions[k]<r.afterFieldVersions[k]||b.fieldVersions[k]===r.afterFieldVersions[k]&&b.fieldValueHashes[k]!==r.afterFieldHashes[k])fail('RECEIPT_VERSION','現在値と適用台帳のrevision・hashが矛盾しています。');}
 }
 for(const c of root.candidates)if(c.targetRecordId&&!root.applicationReceipts.some(r=>r.candidateId===c.id&&r.acceptedRequestId==='raw-only'))fail('RAW_MISSING','登録対象に原値台帳がありません。');
 const session={source,workspaceId:root.workspaceId,runManifest:manifest,candidates:root.candidates,recordBindings:root.recordBindings,applicationReceipts:root.applicationReceipts};return {notebook,session};
}
