import {serializeState} from '../model.js';
import {clone,fail,canonicalJson,byteLength,MAX_SESSION_BYTES,ELIGIBLE_FIELDS} from './common.js';
import {readResearchCsv} from './source.js';
import {createResearchSession,prepareRequest,cancelCandidate,retryUrlJob,acceptResearchResult,reconcileNotebookChange,recordIdentityReview,findCandidate} from './session.js';
import {parseResultFile,validateExchange} from './exchange.js';
import {prepareRawRegistration,prepareResultApplication} from './apply.js';
import {serializeResearchSession,restoreResearchSession} from './backup.js';
import {PUBLIC_RESEARCH_PROMPT,PUBLIC_RESEARCH_PROMPT_VERSION} from './prompt.js';
export function createResearchController({readSnapshot,commitEffect,createId=()=>crypto.randomUUID(),now=()=>new Date().toISOString()}){
 let tail=Promise.resolve(),generation=0;const deps={createId,now};
 const queue=fn=>{const p=tail.then(fn);tail=p.catch(()=>{});return p;};
 const guard=g=>{if(g!==generation)fail('INPUT_STALE','画面終了・ファイル切替により未確定の入力を停止しました。');};
 const commit=async(p,g)=>{const notebookSerialized=serializeState(p.nextNotebook),sessionSerialized=p.nextSession?(await serializeResearchSession(p.nextNotebook,p.nextSession)).json:'';guard(g);if(readSnapshot().revision!==p.baseRevision||!commitEffect({...p,notebookSerialized,sessionSerialized}))fail('REVISION_STALE','手帳が変わりました。現在の内容を再確認してください。');return p;};
 const mutation=fn=>{const snapshot=clone(readSnapshot()),g=generation;return queue(async()=>{guard(g);if(readSnapshot().revision!==snapshot.revision)fail('REVISION_STALE','先の操作が反映されました。もう一度確認してください。');return commit(await fn(snapshot),g);});};
 const proposal=(s,session,message,notebook=s.notebook)=>({baseRevision:s.revision,nextNotebook:notebook,nextSession:session,receipt:{},message});
 const required=s=>{if(!s.session)fail('SESSION','CSVの研究作業を先に開始してください。');};
 const packageRequests=(session,transports)=>{const obj={format:'gourmet-notebook-research-requests',schemaVersion:1,workspaceId:session.workspaceId,promptVersion:PUBLIC_RESEARCH_PROMPT_VERSION,promptText:PUBLIC_RESEARCH_PROMPT,transports};const json=JSON.stringify(obj),bytes=byteLength(json);if(bytes>MAX_SESSION_BYTES||transports.length>1000)fail('REQUEST_CAPACITY','要求ファイルの上限を超えます。');return {json,bytes};};
 return {
  invalidatePendingInputs(){generation++;},
  loadCsv(bytes,name){const g=++generation,snapshot=clone(readSnapshot());return queue(async()=>{guard(g);if(snapshot.session)fail('ACTIVE_SESSION','現在の作業backupを保存し、終了してから別CSVを開始してください。');const extracted=await readResearchCsv(bytes,name,snapshot.notebook.fieldSettings),session=await createResearchSession(snapshot.notebook,extracted,deps);return commit(proposal(snapshot,session,'CSV原本を保全しました。AIは未接続です。'),g);});},
  confirmRaw(decisions,policy){return mutation(async s=>{required(s);if(typeof policy?.allowSequential!=='boolean'||!Array.isArray(policy.allowedFields)||policy.allowedFields.some(k=>!ELIGIBLE_FIELDS.includes(k)))fail('POLICY','空欄補完方針を確認してください。');const p=await prepareRawRegistration(s,decisions,deps);p.nextSession.runManifest.applyPolicy={revision:s.session.runManifest.applyPolicy.revision+1,allowSequential:policy.allowSequential,allowedFields:[...new Set(policy.allowedFields)],confirmedAt:now()};return p;});},
  exportRequests(ids){let result;return mutation(async s=>{required(s);let session=s.session;const transports=[];for(const id of [...new Set(ids)]){const c=findCandidate(session,id);for(const j of c.urlJobs){const p=await prepareRequest(session,id,j.id,s.notebook.fieldSettings,deps);session=p.nextSession;transports.push(p.transport);}}result=packageRequests(session,transports);return proposal(s,session,'公開店名とURLのみの要求を作りました。実行は未接続です。');}).then(()=>result);},
  ingestResults(bytes,name){const g=++generation;return queue(async()=>{guard(g);const parsed=parseResultFile(bytes,name),report={accepted:0,rejected:0,rows:[]};for(const exchange of parsed.exchanges){guard(g);const s=clone(readSnapshot());required(s);let c;try{c=findCandidate(s.session,exchange.candidateId);const attempt=c.history.find(a=>a.transport.request.requestId===exchange.requestId);if(!attempt)fail('UNKNOWN_REQUEST','対応する要求がありません。');const validated=await validateExchange(exchange,attempt.transport,attempt.settingsSnapshot);let p=proposal(s,acceptResearchResult(s.session,validated,deps),'1件のローカル結果を受け取りました。');if(s.session.runManifest.applyPolicy.allowSequential&&c.targetRecordId&&validated.identityVerified&&!exchange.result.needsReview.length&&c.review.applyStatus!=='held')p=await prepareResultApplication(s,c.id,validated,{mode:'sequential'},deps);if(exchange.result.warnings.includes('保存済み観測の変換。観測日を更新せず、ライブ調査として扱いません。'))p.nextSession.runManifest.kind='saved-observation-conversion';await commit(p,g);report.accepted++;report.rows.push({candidateId:c.id,status:'accepted',message:p.message});}
 catch(error){if(['INPUT_STALE','REVISION_STALE'].includes(error.code))throw error;report.rejected++;report.rows.push({candidateId:exchange.candidateId||'',status:'rejected',message:error.message});if(c&&c.activeRequest.transport?.request.requestId===exchange.requestId&&exchange.workspaceId===s.session.workspaceId&&!['STALE','RESULT_CONFLICT','SESSION_CAPACITY','CAPACITY'].includes(error.code)){const session=clone(s.session),row=findCandidate(session,c.id);row.status='failed';row.activeRequest.status='failed';for(const a of [...row.history,...row.urlJobs.flatMap(j=>j.attempts)])if(a.transport.request.requestId===exchange.requestId)a.status='failed';row.review.applyStatus='failed';await commit(proposal(s,session,'この行の結果が不正です。原値と他行は保持します。'),g);}}}return report;});},
  applyOne(id,selectedFields){return mutation(async s=>{required(s);const c=findCandidate(s.session,id);if(!c.result.exchange)fail('RESULT','受入済みの結果がありません。');return prepareResultApplication(s,id,c.result,{mode:'manual',selectedFields},deps);});},
  reviewIdentity(id,review){return mutation(async s=>{required(s);return proposal(s,recordIdentityReview(s.session,id,{...review,now}),'本人の出典確認を記録しました。未確認値は生成しません。');});},
  cancel(id){return mutation(async s=>{required(s);return proposal(s,cancelCandidate(s.session,id,deps),'要求を取り消しました。反映済みの店舗は保持します。');});},
  retry(id,jobId){let transport;return mutation(async s=>{required(s);const p=await retryUrlJob(s.session,id,jobId,s.notebook.fieldSettings,deps);transport=p.transport;return proposal(s,p.nextSession,'新しい要求を作りました。旧結果は失効し、登録先は維持します。');}).then(()=>packageRequests(readSnapshot().session,[transport]));},
  exportSession(){return queue(async()=>{const s=clone(readSnapshot());required(s);return serializeResearchSession(s.notebook,s.session);});},
  restoreSession(bytes,name,{replaceConfirmed=false}={}){const g=++generation,s=clone(readSnapshot());return queue(async()=>{guard(g);if(!replaceConfirmed)fail('RESTORE_CONFIRM','現在の店舗・設定・研究作業を置換する確認が必要です。');const restored=await restoreResearchSession(bytes,name);return commit(proposal(s,restored.session,'研究作業backupを復元しました。',restored.notebook),g);});},
  endSession({discardConfirmed=false}={}){return mutation(async s=>{required(s);if(!discardConfirmed)fail('END_CONFIRM','作業backupの保存を確認して、研究作業の終了を明示してください。');return proposal(s,null,'研究作業を終了しました。手帳の店舗は保持します。');});},
  reconcileNotebook(nextNotebook,intent){return mutation(s=>reconcileNotebookChange(s,nextNotebook,intent,deps));}
 };
}
