import {researchCounts} from './session.js';
import {previewResultApplication} from './apply.js';
import {ELIGIBLE_FIELDS,assertPublicUrl} from './common.js';
const STATUS={waiting:'結果待ち',running:'調査中',confirmed:'確認済（ローカル結果検証）',needs_review:'要確認',failed:'失敗',cancelled:'取消',invalid:'不正行'};
const APPLY={unapplied:'未反映',raw_registered:'原値登録済み',applied:'反映済み',held:'保留',failed:'反映失敗'};
const LABELS={address:'住所',phone:'電話',genre:'ジャンル'};
export function buildResearchViewModel(snapshot){
 const s=snapshot.session;
 return {active:!!s,allowSequential:s?.runManifest.applyPolicy.allowSequential??false,counts:s?researchCounts(s):{},notice:'本人が指定したローカル結果のID・原値・出典・同定を検算します。ブラウザは出典本文へ再アクセスせず、当日の営業を保証しません。AIは未接続です。',persistenceNotice:'再読み込みで消えます。再開には原本・ID・反映台帳を含む作業backupが必要です。',rows:s?s.candidates.map(c=>{
  const result=c.result.exchange?.result;let preview={patch:{},blockedFields:[],reasons:[]};if(result)try{preview=previewResultApplication(snapshot,c.id,c.result);}catch(e){preview.reasons=[e.message];}
  return {id:c.id,name:c.baseRestaurant.name,recordNumber:c.sourceRow.csvRecordNumber,statusLabel:STATUS[c.status],applyLabel:APPLY[c.review.applyStatus],originalMemo:c.sourceRow.cellsByColumn.メモ,originalComment:c.sourceRow.cellsByColumn.コメント,originalRaw:c.sourceRow.rawCsvRecord,targetRecordId:c.targetRecordId,canRegister:c.status!=='invalid'&&(!c.targetRecordId||!!c.review.targetNeedsConfirmation),canApply:!!result&&Object.keys(preview.patch).length>0,canRequest:c.status!=='invalid'&&c.urlJobs.length>0,urlJobs:c.urlJobs,sources:result?.sources??[],unknownFields:result?.unknownFields??[],classificationCandidates:result?.classificationCandidates??[],warnings:[...c.validationErrors,...(c.result.warnings??[]),...(result?.needsReview??[]),...preview.reasons],patch:preview.patch,current: snapshot.notebook.stores.find(s=>s.id===c.targetRecordId),identityChecks:c.review.identityChecks};}):[]};
}
export function mountResearchUI({document,controller,readSnapshot,announce}){
 const $=id=>document.getElementById(id),listeners=[];const on=(el,event,fn)=>{el.addEventListener(event,fn);listeners.push(()=>el.removeEventListener(event,fn));};
 const node=(tag,text='',className='')=>{const n=document.createElement(tag);n.textContent=text;n.className=className;return n;};
 const selections=new Map();let busy=false,fileGeneration=0,disposed=false;
 const status=text=>{$('research-status').textContent=text;announce(text);};
 const download=(data,name)=>{const url=URL.createObjectURL(new Blob([data.json],{type:'application/json;charset=utf-8'})),a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status('ダウンロードを開始しました。保存成功を本人が確認してください。');};
 const run=async fn=>{if(busy)return;busy=true;render();try{await fn();}catch(e){status(e.message);}finally{busy=false;render();}};
 const button=(text,fn,disabled=false)=>{const b=node('button',text,'outline-button');b.type='button';b.disabled=disabled||busy;b.addEventListener('click',()=>run(fn));return b;};
 function render(){if(disposed)return;const snapshot=readSnapshot(),vm=buildResearchViewModel(snapshot);$('research-notice').textContent=vm.notice+' '+vm.persistenceNotice;$('research-counts').textContent=Object.entries(vm.counts).map(([s,n])=>`${STATUS[s]||'反映済み'} ${n}`).join(' / ');
  $('research-policy').disabled=!vm.active||busy;$('research-policy').checked=vm.allowSequential;$('research-confirm-raw').disabled=!vm.active||busy;$('research-requests').disabled=!vm.rows.some(r=>r.canRequest)||busy;$('research-backup').disabled=!vm.active||busy;$('research-end').disabled=!vm.active||busy;$('research-result-file').disabled=!vm.active||busy;$('research-csv').disabled=vm.active||busy;
  const container=$('research-rows');container.replaceChildren();for(const row of vm.rows){const article=node('article','','research-row'),details=node('details'),summary=node('summary',`行${row.recordNumber} ${row.name} · ${row.statusLabel} · ${row.applyLabel}`);details.append(summary);details.append(node('p','元メモ：'+row.originalMemo),node('p','元コメント：'+row.originalComment),node('pre',row.originalRaw,'research-raw'));
   const label=node('label','登録先（共通URLだけでは自動対応しません）'),select=node('select');select.setAttribute('aria-label',`行${row.recordNumber}の登録先`);for(const [value,text]of[['hold','保留'],['new','新しい店舗'],...snapshot.notebook.stores.map(s=>['existing:'+s.id,s.name+'（既存）'])]){const option=node('option',text);option.value=value;select.append(option);}select.value=selections.get(row.id)??'hold';select.disabled=!row.canRegister||busy;select.addEventListener('change',()=>selections.set(row.id,select.value));label.append(select);details.append(label);
   if(row.targetRecordId)details.append(node('p','登録済み対象：'+(row.current?.name||row.targetRecordId)));
   const list=node('ul');for(const field of ELIGIBLE_FIELDS)list.append(node('li',`${LABELS[field]}：現在「${row.current?.[field]||''}」 → ${row.patch[field]?'補完「'+row.patch[field]+'」':row.unknownFields.includes(field)?'不明・空欄保持':'補完なし'}`));details.append(list);
   row.warnings.forEach(w=>details.append(node('p',w,'form-error')));for(const s of row.sources){const link=node('a',`${s.title} / ${s.observedAt} / ${s.accessRoute}`);link.href=assertPublicUrl(s.url);link.target='_blank';link.rel='noopener noreferrer';details.append(link,node('p',s.claim));}
   for(const c of row.classificationCandidates)details.append(node('p',`推測候補（未選択）：${c.placeType} ${c.genre} / ${c.basis}。採用は手動編集で記録します。`));
   const actions=node('div','','research-actions');actions.append(button('この行の空欄を補完',()=>controller.applyOne(row.id,Object.keys(row.patch)).then(p=>status(p.message)),!row.canApply));
   if(row.current){const edit=button('手動で編集・候補を採用',async()=>{$('research-dialog').close();document.dispatchEvent(new CustomEvent('research-edit',{detail:{recordId:row.targetRecordId}}));});actions.append(edit);}
   if(row.sources.length)actions.append(button('出典を読んで対応確認を記録',()=>controller.reviewIdentity(row.id,{decision:'human_confirmed',sourceIds:row.sources.map(s=>s.id),note:'本人が明示的に出典と店舗の対応を確認'}).then(p=>status(p.message))));
   actions.append(button('保留を記録',()=>controller.reviewIdentity(row.id,{decision:'hold',sourceIds:[],note:'本人が保留'}).then(p=>status(p.message))),button('要求を取消',()=>controller.cancel(row.id).then(p=>status(p.message)),!row.canRequest));for(const j of row.urlJobs)actions.append(button('このURLを再試行する要求を保存',async()=>download(await controller.retry(row.id,j.id),'gourmet-research-retry.json'),!row.canRequest));row.identityChecks.forEach(c=>details.append(node('p',`確認記録：${c.decision} / ${c.at} / ${c.note}`)));details.append(actions);article.append(details);container.append(article);}
 }
 const readFile=async(input,action,max)=>{const local=++fileGeneration;controller.invalidatePendingInputs();const file=input.files[0];if(!file)return;await run(async()=>{if(file.size>max)throw Error('ファイル容量上限を超えています。');const bytes=new Uint8Array(await file.arrayBuffer());if(local!==fileGeneration||!$('research-dialog').open)return;await action(bytes,file.name);});input.value='';};
 on($('research-csv'),'change',()=>readFile($('research-csv'),async(b,n)=>{const p=await controller.loadCsv(b,n);status(p.message);},2*1024*1024));
 on($('research-result-file'),'change',()=>readFile($('research-result-file'),async(b,n)=>{const r=await controller.ingestResults(b,n);status(`受入 ${r.accepted}件 / 拒否 ${r.rejected}件。`+r.rows.filter(x=>x.status==='rejected').map(x=>x.message).join(' '));},16*1024*1024));
 on($('research-restore-file'),'change',()=>readFile($('research-restore-file'),async(b,n)=>{const p=await controller.restoreSession(b,n,{replaceConfirmed:$('research-replace-confirm').checked});selections.clear();status(p.message);},16*1024*1024));
 on($('research-policy'),'change',()=>{const checked=$('research-policy').checked;run(async()=>{const p=await controller.confirmRaw({}, {allowSequential:checked,allowedFields:ELIGIBLE_FIELDS});status(p.message+' 補完方針を更新しました。');});});
 on($('research-confirm-raw'),'click',()=>run(async()=>{const decisions=Object.fromEntries(readSnapshot().session.candidates.map(c=>{const v=selections.get(c.id)??'hold';return [c.id,v.startsWith('existing:')?{mode:'existing',recordId:v.slice(9)}:{mode:v}];}));const p=await controller.confirmRaw(decisions,{allowSequential:$('research-policy').checked,allowedFields:ELIGIBLE_FIELDS});status(p.message);}));
 on($('research-requests'),'click',()=>run(async()=>{const ids=buildResearchViewModel(readSnapshot()).rows.filter(r=>r.canRequest).map(r=>r.id);download(await controller.exportRequests(ids),'gourmet-research-requests.json');}));
 on($('research-backup'),'click',()=>run(async()=>download(await controller.exportSession(),'gourmet-research-session.json')));
 on($('research-end'),'click',()=>run(async()=>{const p=await controller.endSession({discardConfirmed:$('research-end-confirm').checked});selections.clear();status(p.message);$('research-end-confirm').checked=false;}));
 on($('research-dialog'),'close',()=>{fileGeneration++;controller.invalidatePendingInputs();});render();return {render,dispose(){disposed=true;listeners.forEach(fn=>fn());controller.invalidatePendingInputs();}};
}
