import test from 'node:test';import assert from 'node:assert/strict';import {fixturePendingResult,fixtureSession,fixedDeps,fixtureExchange} from './research-fixtures.mjs';import {reconcileNotebookChange,acceptResearchResult} from '../research/session.js';
const m=await import('../research/apply.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
test('raw registration is explicit atomic and idempotent with originals kept outside result',async()=>{
 assert.equal(typeof m.prepareRawRegistration,'function');const s=await fixtureSession();const c=s.session.candidates[0],before=JSON.stringify(s);const p=await m.prepareRawRegistration(s,{[c.id]:{mode:'new'}},fixedDeps);assert.equal(JSON.stringify(s),before);assert.equal(p.nextNotebook.stores.length,1);assert.equal(p.nextNotebook.stores[0].memo,'非共有メモ');assert.equal(p.nextSession.candidates[0].sourceRow.cellsByColumn.コメント,'原本コメント');const p2=await m.prepareRawRegistration({notebook:p.nextNotebook,session:p.nextSession,revision:1},{[c.id]:{mode:'new'}},fixedDeps);assert.equal(p2.nextNotebook.stores.length,1);assert.equal(p2.nextSession.applicationReceipts.length,1);
 const preview=m.previewRawRegistration({notebook:p.nextNotebook,session:s.session,revision:0},{[c.id]:{mode:'hold'}});assert.ok(preview.rows[0].duplicateRecordIds.length);
});
test('verified blank patches preserve original values; repeat and retry never append stores',async()=>{
 assert.equal(typeof m.prepareResultApplication,'function');const {snapshot:s,validated:v}=await fixturePendingResult();const before=JSON.stringify(s),c=s.session.candidates[0];const p=await m.prepareResultApplication(s,c.id,v,{mode:'sequential'},fixedDeps);assert.equal(JSON.stringify(s),before);assert.equal(p.nextNotebook.stores[0].address,'架空県合成市1');assert.equal(p.nextNotebook.stores[0].memo,'非共有メモ');assert.deepEqual(p.nextNotebook.stores[0].tags,['非共有タグ']);assert.equal(p.nextSession.applicationReceipts.length,2);
 const repeated=await m.prepareResultApplication({notebook:p.nextNotebook,session:p.nextSession,revision:2},c.id,v,{mode:'sequential'},fixedDeps);assert.equal(repeated.nextSession.applicationReceipts.length,2);assert.equal(repeated.nextNotebook.stores.length,1);
});
test('manual empty touches and changes block late patches, unchecked policy and unresolved identity do not apply',async()=>{
 assert.equal(typeof m.previewResultApplication,'function');const {snapshot:s,validated:v}=await fixturePendingResult();const c=s.session.candidates[0];const edited=await reconcileNotebookChange(s,structuredClone(s.notebook),{kind:'manual',recordId:c.targetRecordId,changedFields:['address'],clearedFields:['address']},fixedDeps);const preview=m.previewResultApplication({notebook:edited.nextNotebook,session:edited.nextSession,revision:2},c.id,v);assert.ok(preview.blockedFields.includes('address'));assert.equal(preview.patch.address,undefined);assert.equal(preview.patch.phone,'00-0000-0000');
 s.session.runManifest.applyPolicy.allowSequential=false;await assert.rejects(m.prepareResultApplication(s,c.id,v,{mode:'sequential'},fixedDeps));await assert.rejects(m.prepareResultApplication(s,c.id,{...v,identityVerified:false},{mode:'manual',selectedFields:['address']},fixedDeps));
});
