import test from 'node:test';import assert from 'node:assert/strict';import {fixturePendingResult,fixtureSession,fixedDeps} from './research-fixtures.mjs';import {prepareResultApplication} from '../research/apply.js';import {reconcileNotebookChange} from '../research/session.js';
const m=await import('../research/backup.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
const bytes=s=>new TextEncoder().encode(s);
test('session backup restores IDs source and receipts; later manual changes never roll back',async()=>{
 assert.equal(typeof m.serializeResearchSession,'function');const {snapshot:s,validated:v}=await fixturePendingResult(),id=s.session.candidates[0].id;const p=await prepareResultApplication(s,id,v,{mode:'sequential'},fixedDeps);const current={notebook:p.nextNotebook,session:p.nextSession,revision:2};const edited=structuredClone(current.notebook);edited.stores[0].address='本人の新住所';const q=await reconcileNotebookChange(current,edited,{kind:'manual',recordId:edited.stores[0].id,changedFields:['address'],clearedFields:[]},fixedDeps);const saved=await m.serializeResearchSession(q.nextNotebook,q.nextSession);const restored=await m.restoreResearchSession(bytes(saved.json),'session.json');assert.equal(restored.notebook.stores[0].id,edited.stores[0].id);assert.equal(restored.notebook.stores[0].address,'本人の新住所');assert.equal(restored.session.candidates[0].sourceRow.cellsByColumn.コメント,'原本コメント');assert.equal(restored.session.applicationReceipts.length,2);
 const repeated=await prepareResultApplication({...restored,revision:3},id,v,{mode:'sequential'},fixedDeps);assert.equal(repeated.nextNotebook.stores.length,1);assert.equal(repeated.nextNotebook.stores[0].address,'本人の新住所');
});
test('backup rejects tampered bytes hashes IDs receipt revisions and unknown keys atomically',async()=>{
 assert.equal(typeof m.restoreResearchSession,'function');const {snapshot:s,validated:v}=await fixturePendingResult();const p=await prepareResultApplication(s,s.session.candidates[0].id,v,{mode:'sequential'},fixedDeps);const saved=await m.serializeResearchSession(p.nextNotebook,p.nextSession);
 for(const mutate of [x=>x.source.bytesBase64='!',x=>x.source.sha256='0'.repeat(64),x=>x.recordBindings[0].fieldValueHashes.memo='0'.repeat(64),x=>x.applicationReceipts[1].afterFieldVersions.address++,x=>x.applicationReceipts[1].patchHash='0'.repeat(64),x=>x.candidates[0].sourceRow.csvRecordNumber++,x=>x.extra=true]){const bad=JSON.parse(saved.json);mutate(bad);await assert.rejects(m.restoreResearchSession(bytes(JSON.stringify(bad)),'session.json'));}
 await assert.rejects(m.restoreResearchSession(bytes(' '.repeat(16*1024*1024+1)),'session.json'));await assert.rejects(m.restoreResearchSession(bytes('{"schemaVersion":2,"format":"gourmet-notebook-prototype"}'),'session.json'));
});
test('whole session input byte boundary accepts exactly 16 MiB and rejects one extra',async()=>{const s=await fixtureSession();const saved=await m.serializeResearchSession(s.notebook,s.session);const exact=saved.json+' '.repeat(16*1024*1024-saved.bytes);assert.equal((await m.restoreResearchSession(bytes(exact),'session.json')).session.workspaceId,s.session.workspaceId);await assert.rejects(m.restoreResearchSession(bytes(exact+' '),'session.json'));});
