import test from 'node:test';import assert from 'node:assert/strict';import {fixtureSession,fixtureSettings,fixedDeps,fixtureExchange,fixtureNotebook,sourceBytes,MAP_URL} from './research-fixtures.mjs';
const m=await import('../research/session.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
test('request shares only title URL, remains waiting and does not mutate source',async()=>{
 assert.equal(typeof m.createResearchSession,'function');const s=await fixtureSession();const before=JSON.stringify(s);const c=s.session.candidates[0];const p=await m.prepareRequest(s.session,c.id,c.urlJobs[0].id,s.notebook.fieldSettings,fixedDeps);
 assert.equal(JSON.stringify(s),before);assert.equal(p.nextSession.candidates[0].status,'waiting');assert.equal(p.nextSession.candidates[0].activeRequest.startedAt,'');assert.equal(p.transport.request.sourceRow.cellsByColumn.メモ,'');assert.equal(p.transport.request.sourceRow.cellsByColumn.コメント,'');assert.ok(!JSON.stringify(p.transport).includes('非共有'));assert.deepEqual(p.transport.request.sharedColumns,['タイトル','URL']);
});
test('cancel and retry invalidate late results while maintaining target; duplicate receipts conflict',async()=>{
 assert.equal(typeof m.prepareRequest,'function');let {notebook,session}=await fixtureSession();const c=session.candidates[0];let p=await m.prepareRequest(session,c.id,c.urlJobs[0].id,notebook.fieldSettings,fixedDeps);session=p.nextSession;const old=p.transport;
 const cancelled=m.cancelCandidate(session,c.id,fixedDeps);assert.equal(cancelled.candidates[0].status,'cancelled');assert.throws(()=>m.acceptResearchResult(cancelled,{exchange:fixtureExchange(old),resultHash:'a',identityVerified:true},fixedDeps));
 session=m.bindCandidateTarget(cancelled,c.id,'kept-target');p=await m.retryUrlJob(session,c.id,c.urlJobs[0].id,notebook.fieldSettings,fixedDeps);assert.equal(p.nextSession.candidates[0].targetRecordId,'kept-target');assert.notEqual(p.transport.request.requestId,old.request.requestId);assert.throws(()=>m.acceptResearchResult(p.nextSession,{exchange:fixtureExchange(old),resultHash:'a',identityVerified:true},fixedDeps));
 const v={exchange:fixtureExchange(p.transport),resultHash:'a',identityVerified:true};const accepted=m.acceptResearchResult(p.nextSession,v,fixedDeps);assert.equal(accepted.candidates[0].status,'confirmed');assert.deepEqual(m.acceptResearchResult(accepted,v,fixedDeps),accepted);assert.throws(()=>m.acceptResearchResult(accepted,{...v,resultHash:'b'},fixedDeps));assert.equal(accepted.candidates[0].review.applyStatus,'unapplied');
});
test('manual touch protects empty fields; settings invalidate requests; append retains old bindings',async()=>{
 assert.equal(typeof m.reconcileNotebookChange,'function');const s=await fixtureSession();s.notebook.stores=[{...s.session.candidates[0].baseRestaurant,id:'record'}];s.session.recordBindings=[await m.makeBinding(s.notebook.stores[0])];s.session=m.bindCandidateTarget(s.session,s.session.candidates[0].id,'record');let p=await m.prepareRequest(s.session,s.session.candidates[0].id,s.session.candidates[0].urlJobs[0].id,s.notebook.fieldSettings,fixedDeps);s.session=p.nextSession;
 const proposal=await m.reconcileNotebookChange(s,structuredClone(s.notebook),{kind:'manual',recordId:'record',changedFields:['address'],clearedFields:['address']},fixedDeps);assert.ok(proposal.nextSession.recordBindings[0].protectedFields.includes('address'));assert.equal(proposal.nextSession.recordBindings[0].fieldVersions.address,1);
 const changed=await m.reconcileNotebookChange(s,s.notebook,{kind:'settings',changedFields:[],clearedFields:[]},fixedDeps);assert.equal(changed.nextSession.candidates[0].activeRequest.requestId,undefined);assert.equal(changed.nextSession.candidates[0].status,'needs_review');await assert.rejects(m.reconcileNotebookChange(s,s.notebook,{kind:'replace'},fixedDeps));
});
