import test from 'node:test';import assert from 'node:assert/strict';import {sourceBytes,fixtureNotebook,fixtureExchange,fixedDeps,MAP_URL} from './research-fixtures.mjs';
const m=await import('../research/controller.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
function harness(){let snapshot={notebook:fixtureNotebook(),session:null,revision:0};const controller=m.createResearchController({readSnapshot:()=>snapshot,commitEffect:e=>{if(e.baseRevision!==snapshot.revision)return false;snapshot={notebook:e.nextNotebook,session:e.nextSession,revision:snapshot.revision+1};return true;},...fixedDeps});return {controller,get:()=>snapshot,bump:()=>snapshot.revision++};}
async function ready(){const h=harness();await h.controller.loadCsv(sourceBytes('合成A,秘密A,'+MAP_URL+',,コメントA\n合成B,秘密B,'+MAP_URL+',,コメントB'),'synthetic.csv');const decisions=Object.fromEntries(h.get().session.candidates.map(c=>[c.id,{mode:'new'}]));await h.controller.confirmRaw(decisions,{allowSequential:true,allowedFields:['address','phone','genre']});const p=await h.controller.exportRequests(h.get().session.candidates.map(c=>c.id));return {...h,requests:JSON.parse(p.json).transports};}
const encoded=x=>new TextEncoder().encode(JSON.stringify(x));
test('controller independently receives reverse arrivals, bad rows, duplicate results and cancellation',async()=>{
 assert.equal(typeof m.createResearchController,'function');const h=await ready();const [a,b]=h.requests;const bad=fixtureExchange(a);bad.inputHash='wrong';const report=await h.controller.ingestResults(encoded({format:'gourmet-notebook-ai-result-batch',schemaVersion:1,exchanges:[fixtureExchange(b),bad]}),'result.json');assert.equal(report.accepted,1);assert.equal(report.rejected,1);assert.equal(h.get().notebook.stores[1].address,'架空県合成市1');assert.equal(h.get().notebook.stores[0].address,'');assert.equal(h.get().session.candidates[0].status,'failed');
 await h.controller.ingestResults(encoded(fixtureExchange(b)),'result.json');assert.equal(h.get().notebook.stores.length,2);assert.equal(h.get().session.applicationReceipts.length,3);await h.controller.cancel(a.request.candidateId);const before=JSON.stringify(h.get());const cancelled=await h.controller.ingestResults(encoded(fixtureExchange(a)),'result.json');assert.equal(cancelled.accepted,0);assert.equal(JSON.stringify(h.get()),before);
});
test('close generation and revision CAS reject stale work without changes',async()=>{
 assert.equal(typeof m.createResearchController,'function');const h=harness();const loading=h.controller.loadCsv(sourceBytes(),'x.csv');h.controller.invalidatePendingInputs();await assert.rejects(loading);assert.equal(h.get().session,null);
 const next=h.controller.loadCsv(sourceBytes(),'x.csv');h.bump();await assert.rejects(next);assert.equal(h.get().session,null);
});
test('settings, explicit empty manual intent and append keep a serializable ledger; ordinary replace requires end',async()=>{
 assert.equal(typeof m.createResearchController,'function');const h=await ready(),c=h.get().session.candidates[0];await h.controller.reconcileNotebook(structuredClone(h.get().notebook),{kind:'manual',recordId:c.targetRecordId,changedFields:['address'],clearedFields:['address']});await h.controller.ingestResults(encoded(fixtureExchange(h.requests[0])),'result.json');assert.equal(h.get().notebook.stores[0].address,'');assert.equal(h.get().notebook.stores[0].phone,'00-0000-0000');await h.controller.reconcileNotebook(h.get().notebook,{kind:'settings'});await h.controller.exportSession();await assert.rejects(h.controller.reconcileNotebook(h.get().notebook,{kind:'replace'}));await assert.rejects(h.controller.endSession({discardConfirmed:false}));await h.controller.endSession({discardConfirmed:true});assert.equal(h.get().session,null);
});
test('16 MiB rejection is atomic for notebook and receipts; failure keeps earlier rows',async()=>{
 const h=await ready();const before=JSON.stringify(h.get());const book=structuredClone(h.get().notebook);const large=structuredClone(h.get().session);large.candidates[0].review.note='x'.repeat(16*1024*1024);const limited=m.createResearchController({readSnapshot:()=>({...h.get(),session:large}),commitEffect:()=>{throw Error('must not commit');},...fixedDeps});await assert.rejects(limited.confirmRaw({}, {allowSequential:true,allowedFields:['address']}),e=>e.code==='SESSION_CAPACITY');assert.equal(JSON.stringify(h.get()),before);assert.equal(JSON.stringify(h.get().notebook),JSON.stringify(book));
});
